name: AWS OIDC Authentication

on:
  push:
    branches:
      - main  # Trigger workflow on push to the main branch

jobs:
  aws-oidc-job:
    runs-on: ubuntu-latest

    permissions:
      id-token: write  # Grant permission to access OIDC token
      contents: read   # Grant permission to read repository contents

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up AWS CLI
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::014498633891:role/terraform-role  # Replace with your role ARN
          aws-region: us-west-2  # Replace with your AWS region

      # Step 3: Run AWS commands or other tasks
      - name: List S3 buckets (example)
        run: aws s3 ls
